kind: Reaction
apiVersion: v1
name: test-agent
spec:
  kind: Agent
  properties:
    AI_SYSTEM_PROMPT: "You are a helpful assistant."
    MCP_SERVERS_CONFIG: > 
      [{ "url": "https://mcp-server-1.com", "apiKey": "abc123" }]
  queries:
    query1: |
      greeting: "Hello, World!"
    query2: |
      greeting: "Howdy!"
