[package]
name = "reactivator"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version = "1.40.0", features = ["full"]}
async-stream = "0.3.5"
drasi-source-sdk = { path = "../.." }
serde_json = "1.0.133"
